### ISSUE TITLE
Prefix for graphite destination

### ISSUE THREAD

**Issue by mgravlin** [peschuster/graphite-client#18]
I see that there is a prefix for statsd output, but not one for Graphite. Does this exist? If not, would be a good enhancement. Without it makes organizing metrics impossible.

**Comment by peschuster** [comment]
The `graphite` configuration element has the `prefixKey` attribute as well.
Is that what you meant?

See https://github.com/peschuster/graphite-client/blob/master/source/Graphite/GraphiteConfiguration.xsd

**Comment by mgravlin** [comment]
Yes it is! I was thrown off by it not being documented in PerfCounterMonitor.exe.config or System-Metrics wiki.
