### ISSUE TITLE
Support connection string

### ISSUE THREAD

**Issue by tkirill** [peschuster/graphite-client#20]
Is it possible to configure the client with connection string?

In our case it would be more convenient than separate configuration section.  We use Octopus for deploying and there we could set connection strings according to environment (stage, production, etc.).

We already do that and `graphite-client` is the only dependency which requires configuration transformation in `*.config` file.

**Comment by peschuster** [comment]
Are you referring to the `connectionStrings` section in configuration file?

I am not shure how specifying a graphite configuration through a connection string would look like.
Could you give an example?

**Comment by tkirill** [comment]
@peschuster Exactly.

Something like this

    <connectionStrings>
      <add name="graphite" connectionString="vm-graphite;port=1234;transport=XXX;prefixkey=\"ZZZ\"" />
      <add name="graphite" connectionString="vm-statsd;port=4321;prefixkey=\"ZZZ\"" />
    </connectionStrings>

**Comment by tkirill** [comment]
Thank you!
