### ISSUE TITLE
EnsureConnected method in TcpPipe is not thread safe.

### ISSUE THREAD

**Issue by rakeshv1** [peschuster/graphite-client#25]
A SocketException is thrown when multiple listeners use the `TcpPipe `to report metrics. 
The exception seems to be thrown when the` tcpClient.Connect` is called inside EnsureConnected method by multiple listeners at the same time.

Possible solutions could be
* Calling `tcpClient.Connect` inside the TcpPipe  constructor 
* Lock around `tcpClient.Connect`

**Comment by peschuster** [comment]
Thanks for reporting the issue.

The `TcpClient` class is not thread safe, therefore the write operation would yield an error, too.
I created a pull request that should fix this problem: #26 

I will need to do some more testing before I merge it into the main branch, but you can test the changes already by using the [threadsafe-tcp](https://github.com/peschuster/graphite-client/tree/threadsafe-tcp) branch.

I'd recommend to use udp for multi-threading applications, though.
