### ISSUE TITLE
When will the next version of Graphite be released to nuget?

### ISSUE THREAD

**Issue by mvickeryJG** [peschuster/graphite-client#34]
Would like to use latest version with the pull request you kindly merged (inject the config into Start()). Thanks!

**Comment by vojtiik** [comment]
Hi @peschuster it would be really great if you could push new nuget package out, even as a pre-release, otherwise can't use your package with .net core due to config issue, which @mvickeryJG fixed  :(.

**Comment by peschuster** [comment]
I just released version 1.3 on nuget, as well as a new binary release of [PerfCounterMonitor.exe](https://github.com/peschuster/graphite-client/releases/tag/Graphite.System_1-1-0-0).
Thanks for your patience.
